[package]
name = "bevy_ui_proxy"
version = "0.1.0"
authors = ["Brett Striker <strikeforcezero@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]

[dependencies.bevy]
version = "0.13"
default-features = false
